// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductDesktop.Database;

#nullable disable

namespace ProductDesktop.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250917084550_Category Enum")]
    partial class CategoryEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductDesktop.Entities.AppUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Password = "admin",
                            Roles = "Admin",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("ProductDesktop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "ElectronicsAndAppliances",
                            Currency = "USD",
                            Name = "Laptop",
                            Price = 999.99000000000001,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "ElectronicsAndAppliances",
                            Currency = "USD",
                            Name = "Smartphone",
                            Price = 599.49000000000001,
                            Stock = 25
                        },
                        new
                        {
                            Id = 3,
                            Category = "HomeAndLiving",
                            Currency = "USD",
                            Name = "Desk Chair",
                            Price = 149.99000000000001,
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = "ElectronicsAndAppliances",
                            Currency = "INR",
                            Name = "Monitor",
                            Price = 199.99000000000001,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            Category = "HomeAndLiving",
                            Currency = "NRS",
                            Name = "Pen",
                            Price = 0.98999999999999999,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
