// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductDesktop.Database;

#nullable disable

namespace ProductDesktop.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250919094422_Fix Supplier Entity")]
    partial class FixSupplierEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductDesktop.Entities.AppUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Password = "admin",
                            Roles = "Admin",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("ProductDesktop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "ElectronicsAndAppliances",
                            Currency = "USD",
                            Name = "Laptop",
                            Price = 999.99000000000001,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "ElectronicsAndAppliances",
                            Currency = "USD",
                            Name = "Smartphone",
                            Price = 599.49000000000001,
                            Stock = 25
                        },
                        new
                        {
                            Id = 3,
                            Category = "HomeAndLiving",
                            Currency = "USD",
                            Name = "Desk Chair",
                            Price = 149.99000000000001,
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = "ElectronicsAndAppliances",
                            Currency = "INR",
                            Name = "Monitor",
                            Price = 199.99000000000001,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            Category = "HomeAndLiving",
                            Currency = "NRS",
                            Name = "Pen",
                            Price = 0.98999999999999999,
                            Stock = 100
                        });
                });

            modelBuilder.Entity("ProductDesktop.Entities.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "ElectronicsAndAppliances",
                            ContactPerson = "John Doe",
                            Description = "Electronic gadgets and accessories",
                            Email = "abc@traders.com",
                            PhoneNumber = "9876543210",
                            SupplierName = "ABC Traders"
                        },
                        new
                        {
                            SupplierId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "FoodAndBeverages",
                            ContactPerson = "Alice Green",
                            Description = "Fresh fruits and vegetables",
                            Email = "alice@freshfarm.com",
                            PhoneNumber = "9876543211",
                            SupplierName = "Fresh Farm Ltd"
                        },
                        new
                        {
                            SupplierId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "HomeAndLiving",
                            ContactPerson = "Bob Smith",
                            Description = "Kitchen and home appliances",
                            Email = "bob@homestyle.com",
                            PhoneNumber = "9876543212",
                            SupplierName = "HomeStyle"
                        },
                        new
                        {
                            SupplierId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "ClothingAndFashion",
                            ContactPerson = "Carol White",
                            Description = "Clothing and fashion accessories",
                            Email = "carol@fashionhub.com",
                            PhoneNumber = "9876543213",
                            SupplierName = "FashionHub"
                        },
                        new
                        {
                            SupplierId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "HomeAndLiving",
                            ContactPerson = "David Brown",
                            Description = "Office supplies and stationery",
                            Email = "david@officeessentials.com",
                            PhoneNumber = "9876543214",
                            SupplierName = "Office Essentials"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
